//Generated by using: "ng generate directive ApplyDefaultArtistImage"
import { Directive, ElementRef, HostListener } from '@angular/core';
import { BaseUrl } from './BaseUrl';

@Directive({
  selector: 'img[appApplyDefaultArtistImage]'
})
export class ApplyDefaultArtistImageDirective {

  constructor(private el: ElementRef, private baseUrl: BaseUrl) { }

  @HostListener('error')
  public onError() {
	  //console.log('Couldnt find image...');
	  //this.el.nativeElement.style.display = "none";
	  this.el.nativeElement.src = `${this.baseUrl.artistImage}/Default.png`;
  }

}
